#!/usr/bin/env node
// scripts/outreach/gate_and_dispatch.js
const fs = require('fs'); const path = require('path'); const { execSync } = require('child_process');
function env(name, def=''){ const v = process.env[name]; return (v===undefined||v===null||v==='') ? def : String(v); }
function nowJST(){ const tz = env('SEND_TZ','Asia/Tokyo'); return new Date(new Date().toLocaleString('en-US', { timeZone: tz })); }
function withinWindow(dt){ const days = env('SEND_DAYS','Mon,Tue,Wed,Thu,Fri').split(',').map(s=>s.trim().toLowerCase()); const startH = parseInt(env('SEND_START_HOUR','9'),10); const endH = parseInt(env('SEND_END_HOUR','20'),10); const wd = ['sun','mon','tue','wed','thu','fri','sat'][dt.getDay()]; const h = dt.getHours(); return days.includes(wd) && h>=startH && h<endH; }
function countEvidence(hours){ const root = path.join(process.cwd(), 'public', 'evidence'); let count = 0; if(!fs.existsSync(root)) return 0; const since = Date.now() - hours*3600*1000; (function walk(d){ for(const e of fs.readdirSync(d,{withFileTypes:true})){ const p = path.join(d, e.name); if (e.isDirectory()) walk(p); else { try{ const st = fs.statSync(p); if (st.mtimeMs >= since) count++; }catch{} } } })(root); return count; }
function gh_api(path, body){ const token = env('GH_TOKEN'); if(!token){ throw new Error('GH_TOKEN missing'); } const repo  = env('GITHUB_REPOSITORY'); const url = `https://api.github.com/repos/${repo}/${path}`; const data = JSON.stringify(body).replace(/'/g,"'\\''"); const cmd = "curl -s -X POST -H 'Authorization: Bearer " + token + "' -H 'Accept: application/vnd.github+json' " + url + " -d '" + data + "'"; return execSync(cmd, {stdio:['ignore','pipe','pipe']}).toString(); }
function findWorkflowIdByNameLike(nameRegex){ const token = env('GH_TOKEN'); if(!token){ throw new Error('GH_TOKEN missing'); } const repo  = env('GITHUB_REPOSITORY'); const out = execSync("curl -s -H 'Authorization: Bearer " + token + "' https://api.github.com/repos/" + repo + "/actions/workflows", {stdio:['ignore','pipe','pipe']}).toString(); const list = JSON.parse(out).workflows || []; const rx = new RegExp(nameRegex, 'i'); const hit = list.find(w => rx.test(w.name) || rx.test(w.path)); return hit ? hit.id : null; }
(function main(){ const dt = nowJST(); const requireChanged = env('REQUIRE_CHANGED_VENDORS','true').toLowerCase()==='true'; const targetToday = parseInt(env('TARGET_EVID_TODAY','10'),10); const lookbackH = parseInt(env('TTD_LOOKBACK_HOURS','48'),10); const dryDefault = env('OUTREACH_DRY_DEFAULT','false'); const limit = env('OUTREACH_LIMIT','12'); const windowH = env('OUTREACH_WINDOW_H','336'); if(!withinWindow(dt)){ console.log('gate: outside send window, skip'); process.exit(0); } const evid = countEvidence(lookbackH); console.log('gate: evidence_in_window=', evid); if(requireChanged && evid < targetToday){ const force = env('FORCE_MIN_SEND','false').toLowerCase()==='true'; if(!force){ console.log('gate: evidence insufficient and FORCE_MIN_SEND=false, skip'); process.exit(0); } } const wid = findWorkflowIdByNameLike('outreach.*triggered|outreach-triggered'); if(!wid){ console.error('gate: cannot find Outreach Triggered workflow'); process.exit(1); } const ref = env('GITHUB_REF_NAME', env('GITHUB_REF','main')); const inputs = { dry: dryDefault, limit, window_h: windowH }; gh_api(`actions/workflows/${wid}/dispatches`, { ref, inputs }); console.log('gate: dispatched Outreach Triggered'); })();
