#!/usr/bin/env node
// scripts/outreach/kpi_guard.js
const fs = require('fs'); const path = require('path');
function env(name, def=''){ const v = process.env[name]; return (v===undefined||v===null||v==='') ? def : String(v); }
function readLines(p){ try{ return fs.readFileSync(p,'utf8').split(/\r?\n/);}catch{return [];} }
function daysAgo(n){ const d=new Date(); d.setDate(d.getDate()-n); return d; }
function mtimeWithin(p, since){ try{ const st = fs.statSync(p); return st.mtime >= since; }catch{return false;} }
function scanCSV(dir, names){ const since = daysAgo(7); let cnt = 0; for(const name of names){ const p = path.join(dir, name); if(!fs.existsSync(p)) continue; if(mtimeWithin(p, since)) { const lines = readLines(p).filter(Boolean); if(lines.length>0 && /[,;]/.test(lines[0])) lines.shift(); cnt += lines.length; } } return cnt; }
function scanLogs(dir, keywords){ const since = daysAgo(7); let cnt = 0; if(!fs.existsSync(dir)) return 0; for(const f of fs.readdirSync(dir)){ const p = path.join(dir,f); if(!mtimeWithin(p, since)) continue; if(/\.(log|json|txt)$/i.test(f)){ const s = fs.readFileSync(p,'utf8').toLowerCase(); if(keywords.some(k=>s.includes(k))) cnt++; } } return cnt; }
(function main(){ const UNSUB_MAX = parseFloat(env('UNSUB_7D_MAX','3')); const COMPL_MAX = parseFloat(env('COMPLAINT_7D_MAX','0.1')); const BOUNCE_MAX = parseFloat(env('BOUNCE_7D_MAX','8')); const unsub = scanCSV('reports', ['unsub.csv','unsubscribe.csv']); const bounces = scanCSV('reports', ['bounces.csv']) + scanLogs('outreach/logs', ['bounce']); const complaints = scanCSV('reports', ['complaints.csv']) + scanLogs('outreach/logs', ['complaint','spamreport']); let sent7 = 0; const sentCsv = path.join('reports','sent.csv'); if (fs.existsSync(sentCsv)) { const lines = readLines(sentCsv); if(lines.length>1) sent7 = lines.length-1; } let complaintRate = 0; if (sent7>0) complaintRate = (complaints / sent7) * 100.0; const breach = { unsub: unsub > UNSUB_MAX, bounce: bounces > BOUNCE_MAX, complaint: complaintRate > COMPL_MAX && sent7>0 }; const any = breach.unsub || breach.bounce || breach.complaint; const out = { unsub, bounces, complaints, sent7, complaintRate: Number(complaintRate.toFixed(2)), thresholds: { UNSUB_7D_MAX: UNSUB_MAX, BOUNCE_7D_MAX: BOUNCE_MAX, COMPLAINT_7D_MAX: COMPL_MAX }, breach }; require('fs').mkdirSync('artifacts', {recursive:true}); require('fs').writeFileSync('artifacts/kpi_guard.json', JSON.stringify(out,null,2)); const dry = any ? 'true' : env('OUTREACH_DRY_DEFAULT','false'); const summary = any ? `BREACH → set dry=${dry}` : `OK → dry=${dry}`; require('fs').writeFileSync(process.env.GITHUB_OUTPUT || 'kpi.out', `outreach_dry=${dry}\nsummary=${summary}\n`); console.log(summary, out); })();