#!/usr/bin/env bash
set -euo pipefail
cd .github/workflows
echo 'Removing apply-theme.yml'; rm -f 'apply-theme.yml'
echo 'Removing auto-accept.yml'; rm -f 'auto-accept.yml'
echo 'Removing build-diff-visuals.yml'; rm -f 'build-diff-visuals.yml'
echo 'Removing build-diffs.yml'; rm -f 'build-diffs.yml'
echo 'Removing build-rss.yml'; rm -f 'build-rss.yml'
echo 'Removing buildwith-import.yml'; rm -f 'buildwith-import.yml'
echo 'Removing categories.yml'; rm -f 'categories.yml'
echo 'Removing channel-grow.yml'; rm -f 'channel-grow.yml'
echo 'Removing check.yml'; rm -f 'check.yml'
echo 'Removing cta-repair.yml'; rm -f 'cta-repair.yml'
echo 'Removing daily-ops.yml'; rm -f 'daily-ops.yml'
echo 'Removing deploy.yml'; rm -f 'deploy.yml'
echo 'Removing diagnose-7d.yml'; rm -f 'diagnose-7d.yml'
echo 'Removing discover-contacts.yml'; rm -f 'discover-contacts.yml'
echo 'Removing domain-grow.yml'; rm -f 'domain-grow.yml'
echo 'Removing emergency-sanitize.yml'; rm -f 'emergency-sanitize.yml'
echo 'Removing final-acceptance.yml'; rm -f 'final-acceptance.yml'
echo 'Removing fix-asset-paths.yml'; rm -f 'fix-asset-paths.yml'
echo 'Removing heartbeat.yml'; rm -f 'heartbeat.yml'
echo 'Removing inbound.yml'; rm -f 'inbound.yml'
echo 'Removing lead-drip.yml'; rm -f 'lead-drip.yml'
echo 'Removing monthly-public-report.yml'; rm -f 'monthly-public-report.yml'
echo 'Removing newlead-autoreply.yml'; rm -f 'newlead-autoreply.yml'
echo 'Removing normalize-evidence.yml'; rm -f 'normalize-evidence.yml'
echo 'Removing obs-daily.yml'; rm -f 'obs-daily.yml'
echo 'Removing on-failure-notify.yml'; rm -f 'on-failure-notify.yml'
echo 'Removing outbound.yml'; rm -f 'outbound.yml'
echo 'Removing probe-public-urls.yml'; rm -f 'probe-public-urls.yml'
echo 'Removing promote-intakes.yml'; rm -f 'promote-intakes.yml'
echo 'Removing public-change-poller.yml'; rm -f 'public-change-poller.yml'
echo 'Removing restore-home.yml'; rm -f 'restore-home.yml'
echo 'Removing seo-pages.yml'; rm -f 'seo-pages.yml'
echo 'Removing seo-ping.yml'; rm -f 'seo-ping.yml'
echo 'Removing seo-tighten.yml'; rm -f 'seo-tighten.yml'
echo 'Removing site-doctor.yml'; rm -f 'site-doctor.yml'
echo 'Removing site-repair.yml'; rm -f 'site-repair.yml'
echo 'Removing vendor-catalog.yml'; rm -f 'vendor-catalog.yml'
echo 'Removing vendors-slug-unify.yml'; rm -f 'vendors-slug-unify.yml'
echo 'Removing weekly-hash-announce.yml'; rm -f 'weekly-hash-announce.yml'
echo 'Removing weekly-report.yml'; rm -f 'weekly-report.yml'
echo 'Done. Commit and push the cleanup.'
