name = "cg-alert-kv-editor"
main = "index.js"
compatibility_date = "2024-08-01"
[[kv_namespaces]]
binding = "FILTERS"
id = "<KV_NAMESPACE_ID>"
[vars]
# ENABLE_DISPATCH="true"
# GH_REPO="<owner>/<repo>"
[observability]
enabled = true
