#!/usr/bin/env bash
#
# run_acceptance.sh
#
# Final acceptance gate. If this passes, pipeline can run mostly unattended:
# - target discovery -> targets.csv
# - lead enrich -> leads.csv
# - vendor expand -> endpoints.json
# - evidence harvest -> dashboard
# - outreach -> Stripe/intake
# - suppression / bounce / unsubscribe loop
# - legal footer / terms / privacy / DPA present
# - pricing CTA synced
# - site self-heals
#
set -euo pipefail

red(){ echo -e "\033[31m✗ $*\033[0m"; }
grn(){ echo -e "\033[32m✓ $*\033[0m"; }
ylw(){ echo -e "\033[33m! $*\033[0m"; }
fail(){ red "$1"; exit 1; }

need_paths=(
  "lead-gateway/src/index.js"
  "lead-gateway/wrangler.toml"
  "_redirects"
  "index.html"
  "enterprise/index.html"
  "rss.xml"
  "sitemap.xml"
  "package.json"
  "pricing/config.json"
  "config/verticals.json"
  "config/targets.csv"
  "config/endpoints.json"
  "scripts/poll_inbox.js"
  "scripts/repair_pages.js"
  "scripts/intake_sync_kv.js"
  "scripts/sync_unsub_kv.js"
  "scripts/suppression_apply.js"
  "scripts/send_triggered.js"
  "scripts/poll_public_endpoints.js"
  "scripts/build_dashboard.js"
  "scripts/lead_enrich_sync.js"
  "scripts/discover_targets.js"
  "scripts/expand_endpoints.js"
  "scripts/pricing_sync.js"
  "scripts/legal_stamp.js"
  "scripts/weekly_health_check.js"
  "scripts/workflows_doctor.js"
  "scripts/merge_public_into_root.sh"
  "scripts/run_acceptance.sh"
  "data/leads.csv"
  "data/intakes.csv"
  "data/customers.csv"
  "legal"
  ".github/workflows/stabilize.yml"
  ".github/workflows/intake-sync.yml"
  ".github/workflows/outreach-triggered.yml"
  ".github/workflows/bounce-sweep.yml"
  ".github/workflows/suppression-sync.yml"
  ".github/workflows/evidence-harvest.yml"
  ".github/workflows/lead-enrich.yml"
  ".github/workflows/weekly-health-check.yml"
  ".github/workflows/workflows-doctor.yml"
  ".github/workflows/check-secrets.yml"
  ".github/workflows/pricing-sync.yml"
  ".github/workflows/legal-health.yml"
  ".github/workflows/vendor-expand.yml"
  ".github/workflows/target-discovery.yml"
)

for p in "${need_paths[@]}"; do
  if [ ! -e "$p" ]; then
    fail "MISSING: $p"
  fi
done
grn "Key files/directories exist OK"

# redirects sanity
grep -Eq "/buy/portfolio" _redirects || fail "_redirects missing /buy/portfolio → Stripe Payment Link"
grep -Eq "/intake" _redirects || ylw "_redirects missing /intake 302 (lead intake form)"

# CTA sanity
grep -RIl "Buy Portfolio" index.html enterprise dashboard 2>/dev/null   || ylw "CTA 'Buy Portfolio' not found in site (check pricing_sync / index.html template)"

# legal sanity
grep -RIl "Privacy Policy" legal 2>/dev/null   || ylw "legal pages missing Privacy Policy wording (will be generated by legal_stamp.js via legal-health.yml)"
grep -RIl "Terms of Service" legal 2>/dev/null   || ylw "legal pages missing Terms of Service wording (will be generated by legal_stamp.js via legal-health.yml)"

echo
grn "ACCEPTANCE PASS BASELINE: automated growth, outreach, compliance, and monetization loop is structurally intact."
