#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""send_digests_via_webhook.py
Optional step to deliver generated digests to an external mail-gateway / webhook.

Design:
- This script is **safe by default**:
  - If neither per-customer `webhook_url` nor the global `DIGEST_WEBHOOK_URL`
    are configured, it does nothing and exits 0.
  - Network / HTTP errors are logged to stderr but do **not** cause a non‑zero exit
    code, so CI workflows stay green.
- Inputs:
  - artifacts/digests/*.txt      (generated by gen_customer_digests.py)
  - customers from CUSTOMERS_API_URL (preferred) or config/customers.json /
    config/customers.example.json (fallback).
- For each customer that has a digest file and at least one webhook target,
  this script POSTs a JSON payload:

    {
      "customer_id": "...",
      "plan": "...",
      "email": "...",
      "cc": [...],
      "frequency": "weekly",
      "subject": "...",
      "body": "<plain text digest>",
    }

  to either:
    - customer['webhook_url'], if present, else
    - the global DIGEST_WEBHOOK_URL environment variable.

It is intentionally minimal – the external gateway is responsible for
deciding whether to send email, enqueue jobs, etc.
"""

import json
import os
import sys
import pathlib
import urllib.request
import urllib.error
from typing import Any, Dict, List

ROOT = pathlib.Path(__file__).resolve().parent.parent
DIGEST_DIR = ROOT / "artifacts" / "digests"

def log(*xs: Any) -> None:
    print(*xs, file=sys.stderr)

def load_customers() -> List[Dict[str, Any]]:
    """Best-effort customer loader.

    Priority:
      1) CUSTOMERS_API_URL (JSON list or wrapped in {items|customers|data})
      2) config/customers.json
      3) config/customers.example.json

    Any parsing / network error results in an empty list, but we still exit 0.
    """
    api_url = (os.environ.get("CUSTOMERS_API_URL", "") or "").strip()
    if api_url:
        try:
            req = urllib.request.Request(
                api_url,
                headers={"User-Agent": "cg-alert-digests-webhook/1.0"},
            )
            with urllib.request.urlopen(req, timeout=10) as resp:
                raw = resp.read().decode("utf-8", errors="replace")
            data = json.loads(raw)
            if isinstance(data, list):
                return data
            if isinstance(data, dict):
                for key in ("items", "customers", "data"):
                    if isinstance(data.get(key), list):
                        return list(data[key])
        except Exception as e:  # noqa: BLE001
            log("WARN: CUSTOMERS_API_URL fetch failed:", e)

    cfg = ROOT / "config" / "customers.json"
    ex = ROOT / "config" / "customers.example.json"
    path = cfg if cfg.exists() else ex
    if not path.exists():
        log("WARN: no customers.json/example.json; nothing to send")
        return []
    try:
        with path.open("r", encoding="utf-8") as f:
            data = json.load(f)
        if isinstance(data, list):
            return data
        log("WARN: customers file is not a list – ignoring")
    except Exception as e:  # noqa: BLE001
        log("WARN: failed to read customers config:", e)
    return []

def pick_webhook(customer: Dict[str, Any]) -> str:
    per_customer = (customer.get("webhook_url") or "").strip()
    if per_customer:
        return per_customer
    global_url = (os.environ.get("DIGEST_WEBHOOK_URL", "") or "").strip()
    return global_url

def build_payload(cid: str, customer: Dict[str, Any], body: str) -> Dict[str, Any]:
    subject = f"CG Alert digest for {cid}"
    email = (customer.get("email") or "").strip()
    freq = (customer.get("frequency") or "weekly").strip()
    return {
        "customer_id": cid,
        "plan": customer.get("plan") or "",
        "email": email or None,
        "cc": customer.get("cc") or [],
        "frequency": freq,
        "subject": subject,
        "body": body,
    }

def post_json(url: str, payload: Dict[str, Any]) -> None:
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=data,
        headers={
            "User-Agent": "cg-alert-digests-webhook/1.0",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            # We intentionally ignore the body; log status for debugging only.
            log("INFO: posted digest to", url, "status", resp.getcode())
    except urllib.error.HTTPError as e:
        log("WARN: HTTP error posting digest to", url, "status", e.code)
    except Exception as e:  # noqa: BLE001
        log("WARN: network error posting digest to", url, "err:", e)

def main() -> int:
    if not DIGEST_DIR.exists():
        log("INFO: digest directory does not exist; nothing to send")
        return 0

    customers = load_customers()
    if not customers:
        log("INFO: no customers loaded; nothing to send")
        return 0

    sent = 0
    skipped = 0

    # Build a map for quick lookup by id (string)
    # If a customer has no id, we derive one from email as best-effort.
    by_id: Dict[str, Dict[str, Any]] = {}
    for c in customers:
        cid = (c.get("id") or c.get("email") or "").strip()
        if not cid:
            continue
        by_id[cid] = c

    for path in sorted(DIGEST_DIR.glob("*.txt")):
        cid = path.stem
        customer = by_id.get(cid)
        if not customer:
            log(f"WARN: no customer config found for digest {cid}.txt – skipping")
            skipped += 1
            continue

        url = pick_webhook(customer)
        if not url:
            log(f"INFO: no webhook configured for customer {cid}; skipping send")
            skipped += 1
            continue

        try:
            body = path.read_text(encoding="utf-8")
        except Exception as e:  # noqa: BLE001
            log(f"WARN: failed to read digest file for {cid}:", e)
            skipped += 1
            continue

        payload = build_payload(cid, customer, body)
        post_json(url, payload)
        sent += 1

    log("Done send_digests_via_webhook.py; sent:", sent, "skipped:", skipped)
    # Always exit 0 to avoid breaking CI; delivery reliability is handled downstream.
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
