name: Actionlint

on:
  pull_request:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/*.yml'

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run actionlint via reviewdog
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          level: error
          fail_on_error: true
